foreground #f3dde2
background #0d121e
cursor     #ffb0c8

selection_foreground #650033
selection_background #ffb0c8

color0  #151d30
color8  #a58a91
color1  #ffb4ab
color9  #ffb4ab
color2  #8a77cd
color10 #8a77cd
color3  #ffb0c8
color11 #ffb0c8
color4  #ffb0c8
color12 #ffb0c8
color5  #ee5c95
color13 #ee5c95
color6  #8a77cd
color14 #8a77cd
color7  #ddbfc6
color15 #f3dde2
