[config]
reload_apps = false

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar-colors.css"
output_path = "~/.config/waybar/tokens/colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-theme.lua"
output_path = "~/.config/hypr/hyprland/theme.lua"
post_hook = "hyprctl reload"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock-colors.conf"
output_path = "~/.config/hypr/hyprlock-colors.conf"

[templates.sddm]
input_path = "~/.config/matugen/templates/sddm-colors.conf"
output_path = "~/.config/sddm/theme-colors.conf"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-3.0/gtk.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-4.0/gtk.css"

[templates.eww]
input_path = "~/.config/matugen/templates/eww-colors.scss"
output_path = "~/.config/eww/_colors.scss"
post_hook = "eww reload || true"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/kitty-theme.conf"
post_hook = "pkill -SIGUSR1 -x kitty || true"

[templates.wlogout]
input_path = "~/.config/matugen/templates/wlogout-colors.css"
output_path = "~/.config/wlogout/colors.css"

[templates.qt6]
input_path = "~/.config/matugen/templates/qt-palette.conf"
output_path = "~/.config/qt6ct/colors/matugen.conf"

[templates.qt5]
input_path = "~/.config/matugen/templates/qt-palette.conf"
output_path = "~/.config/qt5ct/colors/matugen.conf"

[templates.satty]
input_path = "~/.config/matugen/templates/satty-overrides.css"
output_path = "~/.config/satty/overrides.css"

[templates.spotify-player]
input_path = "~/.config/matugen/templates/spotify-player-theme.toml"
output_path = "~/.config/spotify-player/theme.toml"

[templates.swaync]
input_path = "~/.config/matugen/templates/swaync-colors.css"
output_path = "~/.config/swaync/tokens/variables.css"
post_hook = "swaync-client -rs || true"
