$primary    = rgb(ffb0c8)
$on_primary = rgb(650033)
$on_surface = rgb(f3dde2)
$muted      = rgb(ddbfc6)
$outline    = rgb(a58a91)
$surface    = rgb(0d121e)
$tertiary   = rgb(8a77cd)
$error      = rgb(ffb4ab)
