general {
    lock_cmd = pidof hyprlock || ~/.config/hypr/scripts/lock.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl eval "hl.dispatch(hl.dsp.dpms('on'))"
    ignore_dbus_inhibit = false
}

listener {
    timeout = 300
    on-timeout = brightnessctl -s set 20%
    on-resume = brightnessctl -r
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {
    timeout = 720
    on-timeout = hyprctl eval "hl.dispatch(hl.dsp.dpms('off'))"
    on-resume = hyprctl eval "hl.dispatch(hl.dsp.dpms('on'))"
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
