[General]
Font="Adwaita Sans"
FontSize="12"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="backgrounds/cinder.mp4"

AnimationDuration="300"
AnimationEasing="OutQuart"

AutoFingerprintOnLoad=false
AutoRotateBackground=true
AvatarDir="/home/zufi/Pictures/avatars"

ThemeColorsFile="/home/zufi/.config/sddm/theme-colors.conf"

StartupBackgroundColor="#0d171e"

DateTextColor="#f2ffffff"
TimeTextColor="#ffb3b1"

FormBackgroundColor="#08080a"

LoginFieldBackgroundColor="#ffffff"
PasswordFieldBackgroundColor="#ffffff"

LoginFieldTextColor="#ffffff"
PasswordFieldTextColor="#ffffff"

PlaceholderTextColor="#b3ffffff"

FocusBorderColor="#ffb3b1"

LoginButtonTextColor="#611117"
LoginButtonBackgroundColor="#ffb3b1"

SystemButtonsIconsColor="#e6ffffff"
EnvironmentButtonTextColor="#b3ffffff"

DropdownTextColor="#f1dedd"
DropdownSelectedTextColor="#611117"
DropdownBackgroundColor="#142430"
DropdownSelectedBackgroundColor="#ffb3b1"
DropdownBorderColor="#26ffffff"
DropdownSelectedBorderColor="#ffb3b1"

HoverLoginButtonBackgroundColor="#ab494a"
HoverSystemButtonsIconsColor="#ffb3b1"
HoverEnvironmentButtonTextColor="#ffb3b1"

Blur="0.0"
FormPosition="center"
