TimeTextColor="{{colors.primary.default.hex}}"
LoginButtonBackgroundColor="{{colors.primary.default.hex}}"
LoginButtonTextColor="{{colors.on_primary.default.hex}}"
HoverLoginButtonBackgroundColor="{{colors.primary_container.default.hex}}"
HoverSystemButtonsIconsColor="{{colors.primary.default.hex}}"
HoverEnvironmentButtonTextColor="{{colors.primary.default.hex}}"
DropdownBackgroundColor="{{colors.surface_container.default.hex}}"
DropdownTextColor="{{colors.on_surface.default.hex}}"
DropdownSelectedBackgroundColor="{{colors.primary.default.hex}}"
DropdownSelectedTextColor="{{colors.on_primary.default.hex}}"
DropdownSelectedBorderColor="{{colors.primary.default.hex}}"
FocusBorderColor="{{colors.primary.default.hex}}"
StartupBackgroundColor="{{colors.surface.default.hex}}"
