[[themes]]
name = "glass"

[themes.palette]
background = "{{colors.surface.default.hex}}"
foreground = "{{colors.on_surface.default.hex}}"
black = "{{colors.surface_container.default.hex}}"
red = "{{colors.error.default.hex}}"
green = "{{colors.tertiary.default.hex}}"
yellow = "{{colors.secondary.default.hex}}"
blue = "{{colors.primary.default.hex}}"
magenta = "{{colors.primary_container.default.hex}}"
cyan = "{{colors.tertiary_fixed_dim.default.hex}}"
white = "{{colors.on_surface_variant.default.hex}}"
bright_black = "{{colors.outline.default.hex}}"
bright_red = "{{colors.error.default.hex}}"
bright_green = "{{colors.tertiary.default.hex}}"
bright_yellow = "{{colors.secondary.default.hex}}"
bright_blue = "{{colors.primary.default.hex}}"
bright_magenta = "{{colors.primary.default.hex}}"
bright_cyan = "{{colors.tertiary_fixed_dim.default.hex}}"
bright_white = "{{colors.on_surface.default.hex}}"
